version: '3.5'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'remind'
      MYSQL_USER: 'remind'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    expose:
      - 3306
    ports:
      - 3306:3306

  redis:
    image: "redis:alpine"

  app:
    build: .
    command: bash -c "python /reminder/manage.py migrate --noinput && python /reminder/manage.py runserver 0.0.0.0:8000"
    env_file:
      - prod.env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - ./reminder:/reminder/
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A reminder worker -l info
    env_file:
      - prod.env
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
    volumes:
      - ./reminder:/reminder/
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A reminder beat -l info
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./reminder:/reminder/
    depends_on:
      - db
      - redis
