# Generated by Django 2.2.7 on 2019-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
